name: build_cloud_v2

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build_cloud_v2
  cancel-in-progress: false

jobs:
  build_cloud_v2:
    uses: ./.github/workflows/build_branch.yaml
    with:
      branch: cloud_v2
